In [1]:
import sys, os
sys.path.append("../..")

# import gempy
import gempy as gp

# inline figures in jupyter notebooks
import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
import pandas as pn
from importlib import reload

In [2]:
import gempy.utils.geomodeller_integration as gi

In [3]:
gi

<module 'gempy.utils.geomodeller_integration' from '../..\\gempy\\utils\\geomodeller_integration.py'>

In [4]:
geoM = gi.GeomodellerClass()

In [5]:
geoM.load_geomodeller_file('../../test/GeoModeller/test_d/test_d.xml')

In [6]:
geoM.get_sections()

[<Element '{http://www.geomodeller.com/geo}Section' at 0x0000017568B94868>,
 <Element '{http://www.geomodeller.com/geo}Section' at 0x0000017568B9F188>]

In [7]:
geoM.get_faults()

[<Element '{http://www.geomodeller.com/geo}Fault' at 0x0000017568B94638>]

In [8]:
geoM.faults[0].get("Name")

'f1'

In [9]:
geoM.get_formations()

In [10]:
geoM.formations

[<Element '{http://www.geomodeller.com/geo}Formation' at 0x0000017568B789F8>,
 <Element '{http://www.geomodeller.com/geo}Formation' at 0x0000017568B8C3B8>]

In [11]:
geoM.get_formation_names()

['A', 'B']

In [12]:
geoM.get_fault_names

<bound method GeomodellerClass.get_fault_names of <gempy.utils.geomodeller_integration.GeomodellerClass object at 0x0000017568A23B70>>

In [13]:
geoM.get_stratigraphy_list()

['B', 'A']

In [14]:
geoM.get_fault_parameters()

AttributeError: 'GeomodellerClass' object has no attribute 'get_fault_parameters'

In [15]:
geoM.create_formation_dict()

{'A': <Element '{http://www.geomodeller.com/geo}Formation' at 0x0000017568B789F8>,
 'B': <Element '{http://www.geomodeller.com/geo}Formation' at 0x0000017568B8C3B8>}

In [22]:
geoM.create_fault_dict()

{'f1': <Element '{http://www.geomodeller.com/geo}Fault' at 0x7fa938261818>}

In [23]:
geoM.get_model_extent()

(0.0, 10.0, 0.0, 10.0, -10.0, 0.0)

In [31]:
geoM.rootelement.find("{"+geoM.xmlns+"}GeologicalModel").find("{"+geoM.xmlns+"}Extent3D").find("{"+geoM.xmlns+"}ExtentZ").get("Zmin")

'-10.0'

In [33]:
stc =geoM.rootelement.find("{"+geoM.xmlns+"}GeologicalModel").find("{"+geoM.xmlns+"}ProjectStratigraphicColumn")

In [35]:
stc.find("{"+geoM.gml+"}coord")

In [40]:
inter = stc.find("{"+geoM.xmlns+"}Series").find("{"+geoM.xmlns+"}PotentialField").find("{"+geoM.xmlns+"}Points")

In [50]:
p = inter.find("{"+geoM.gml+"}coord").findtext("{"+geoM.gml+"}X")

In [49]:
p.text

'2.0477319587628866059958454570733010768890380859375'

In [51]:
p

'2.0477319587628866059958454570733010768890380859375'

---

# ReadGeoModellerXML class

In [17]:
reload(gp.utils.geomodeller_integration);
gmx = gp.utils.geomodeller_integration.ReadGeoModellerXML("NorthPerthBasin_rev.xml")

The **ElementTree** root of the read-in xml file is accessible via:

In [231]:
gmx.root

<Element '{http://www.geomodeller.com/geo}Project3DEdit' at 0x000002067548E048>

**Interfaces** dataframe:

In [10]:
gmx.get_interfaces_df().tail()

X          Y    Z            formation               series
11306  328362.0  6758890.0  0.0  Fault_Transverse_03  Fault_Transverse_03
11307  337144.0  6751190.0  0.0  Fault_Transverse_03  Fault_Transverse_03
11308  347951.0  6741460.0  0.0  Fault_Transverse_03  Fault_Transverse_03
11309  359483.0  6730450.0  0.0  Fault_Transverse_03  Fault_Transverse_03
11310  364864.0  6725480.0  0.0  Fault_Transverse_03  Fault_Transverse_03

**Orientations** dataframe:

In [18]:
gmx.get_orientation_df().tail()

X            Y            Z       dip   azimuth  polarity  \
100  354192.0742  6804450.074 -30735.74609   3.56591  228.5130         1   
101  289338.0957  6598540.672 -10028.23730  13.75430   51.8948         1   
102  398679.2813  6629800.047 -15358.76563   1.27821  156.4510         1   
103  307179.2813  6736300.070 -14392.41309   3.72760   62.6046         1   
104  354192.0742  6804450.074 -14920.71973   0.18586  289.6310         1   

       formation             series  
100         Moho         Moho_Serie  
101  Lower_crust  Lower_crust_Serie  
102  Lower_crust  Lower_crust_Serie  
103  Lower_crust  Lower_crust_Serie  
104  Lower_crust  Lower_crust_Serie

**Extent**:

In [224]:
gmx.extent

(259000.0, 415000.0, 6568000.0, 6848000.0, -45000.0, 500.0)

The **stratigraphic column** as found in the xml (ordered from old to young):

In [225]:
gmx.strat_column

('Moho_Serie',
 'Lower_crust_Serie',
 'Yigarn_Series',
 'Precambrian',
 'Permian',
 'Triassic-Jurassic',
 'Neocomian_Unconformity',
 'Topo_and_bathy_Series',
 'Sea_level_Series')

**Faults** ordered as found in the xml:

In [226]:
gmx.faults

('Fault_01',
 'Fault_02_Beagle',
 'Fault_03_Wedge',
 'Fault_04',
 'Fault_05',
 'Fault_06_Peron',
 'Fault_08_Coomallo',
 'Fault_09',
 'Fault_10_Eneabba',
 'Fault_11',
 'Fault_12_Urella',
 'Fault_13_Darling',
 'Fault_14_Peron',
 'Fault_Transverse_01',
 'Fault_Transverse_02_Abrolhos',
 'Fault_Transverse_03')

Which formations belongs to which series encoded in a dictionary:

In [290]:
gmx.series_distribution

{'Lower_crust_Serie': 'Lower_crust',
 'Moho_Serie': 'Moho',
 'Neocomian_Unconformity': 'Neocomian_Unc',
 'Permian': 'Late_Permian',
 'Precambrian': 'Basement',
 'Sea_level_Series': 'Sea_level',
 'Topo_and_bathy_Series': 'Topo_and_bathy',
 'Triassic-Jurassic': ('Kockatea_Shale',
  'Woodada_Fm',
  'Lesueur_Ss',
  'Eneabba_Fm',
  'Cattamarra_Coal_Measures',
  'Yarragadee_Fm'),
 'Yigarn_Series': 'Yigarn'}

Getting the **fault matrix**, where **1** means the fault stops at the other fault:

In [292]:
print(gmx.get_fault_matrix())

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0. 

In [309]:
gmx.get_order_formations()

['Moho',
 'Lower_crust',
 'Yigarn',
 'Basement',
 'Late_Permian',
 'Kockatea_Shale',
 'Woodada_Fm',
 'Lesueur_Ss',
 'Eneabba_Fm',
 'Cattamarra_Coal_Measures',
 'Yarragadee_Fm',
 'Neocomian_Unc',
 'Topo_and_bathy',
 'Sea_level']

## Dev

In [4]:
gmx.get_order_formations()

['Moho',
 'Lower_crust',
 'Yigarn',
 'Basement',
 'Late_Permian',
 'Kockatea_Shale',
 'Woodada_Fm',
 'Lesueur_Ss',
 'Eneabba_Fm',
 'Cattamarra_Coal_Measures',
 'Yarragadee_Fm',
 'Neocomian_Unc',
 'Topo_and_bathy',
 'Sea_level']

In [21]:
gmx.strat_column

('Moho_Serie',
 'Lower_crust_Serie',
 'Yigarn_Series',
 'Precambrian',
 'Permian',
 'Triassic-Jurassic',
 'Neocomian_Unconformity',
 'Topo_and_bathy_Series',
 'Sea_level_Series')

In [2]:
geo_data, gmx = gp.create_from_geomodeller_xml("NorthPerthBasin_rev.xml")